name: projects3
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  provider: ^6.0.2
  flutter_localizations:
    sdk: flutter
  datetime_picker_formfield: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
